api_token: <SLACK API TOKEN>

bot_id: <BOT SLACK ID>

server_host: <SERVER HOST ADDRESS>

server_token: <SERVER HOST REST FRAMEWORK TOKEN>

# slack IDs of all NFC bots
nfc_bots:
  - U123
  - U456

# PLUGIN / COMMANDS

record_emojis:
  - beers
  - partyparrot
  - sunglasses
  - ambulance
  - champagne
  - muscle
  - boom
