api_token: <SLACK API TOKEN>

bot_id: <BOT SLACK ID>

server_host: <SERVER HOST ADDRESS>

server_token: <SERVER HOST REST FRAMEWORK TOKEN>

nfc_london: <LONDON NFC SLACK ID>
nfc_bristol: <BRISTOL NFC SLACK ID>

# PLUGIN / COMMANDS

record_emojis:
  - beers
  - partyparrot
  - sunglasses
  - ambulance
  - champagne
  - muscle
  - boom
